#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "ZGMw7/LvRp3y"
#define LAYER_STATE_8BIT

#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 6
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

